version: "3.8"
services:
  mirr-web-server:
    container_name: mirr-server
    build: .
    depends_on:
      - mirr-record-database
    image: jihoon0413/mirr-server
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - 8080:8080

  mirr-record-database:
    container_name: mirr-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: jihoon0413/mirr-database
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"




