spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-red-sun-a1d8c5wk.ap-southeast-1.pg.koyeb.app/${STAGING_DBNAME}
    username: ${STAGING_DATASOURCE_USERNAME}
    password: ${STAGING_DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always