spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mirr-record-database:3306/mirr
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always