insert into player (name, pos, back_num) values ('박동렬', 'CM', 8);
insert into player (name, pos, back_num) values ('서호종', 'DF', 54);
insert into player (name, pos, back_num) values ('이창훈', 'CF', 6);
insert into player (name, pos, back_num) values ('송효종', 'CM', 26);
insert into player (name, pos, back_num) values ('이창준', 'CM', 9);
insert into player (name, pos, back_num) values ('국민성', 'CM',14);
insert into player (name, pos, back_num) values ('정형기', 'CM', 40);
insert into player (name, pos, back_num) values ('김용찬', 'CM',000);
insert into player (name, pos, back_num) values ('안병용', 'CM', 11);
insert into player (name, pos, back_num) values ('조규룡', 'CM', 33);
insert into player (name, pos, back_num) values ('차웅재', 'CM', 99);
insert into player (name, pos, back_num) values ('노형남', 'CM', 3);
insert into player (name, pos, back_num) values ('박정희', 'CM', 000);
insert into player (name, pos, back_num) values ('임성규', 'CM', 45);
insert into player (name, pos, back_num) values ('고준민', 'CM', 39);
insert into player (name, pos, back_num) values ('고대운', 'CM', 16);
insert into player (name, pos, back_num) values ('김현식', 'CM', 59);
insert into player (name, pos, back_num) values ('이우열', 'CM', 67);
insert into player (name, pos, back_num) values ('정한철', 'CM', 1);
insert into player (name, pos, back_num) values ('고영석', 'CM', 000);
insert into player (name, pos, back_num) values ('박주영', 'CM', 000);
insert into player (name, pos, back_num) values ('봉세종', 'CM', 98);
insert into player (name, pos, back_num) values ('박상무', 'CM', 80);
insert into player (name, pos, back_num) values ('김영빈', 'CM', 2);
insert into player (name, pos, back_num) values ('유찬재', 'CM', 55);
insert into player (name, pos, back_num) values ('김영재', 'CM', 25);
insert into player (name, pos, back_num) values ('고재성', 'CM', 48);
insert into player (name, pos, back_num) values ('정태웅', 'CM', 000);
insert into player (name, pos, back_num) values ('김우형', 'CM', 24);
insert into player (name, pos, back_num) values ('신지훈', 'CM', 43);
insert into player (name, pos, back_num) values ('이성완', 'CM', 88);
insert into player (name, pos, back_num) values ('김민석', 'CM', 22);
insert into player (name, pos, back_num) values ('정다운', 'CM', 000);
insert into player (name, pos, back_num) values ('김강민', 'CM', 52);
insert into player (name, pos, back_num) values ('김효준', 'CM', 21);
insert into player (name, pos, back_num) values ('송준민', 'CM', 23);
insert into player (name, pos, back_num) values ('유재호', 'CM', 93);
insert into player (name, pos, back_num) values ('서호연', 'CM', 55);
insert into player (name, pos, back_num) values ('양진서', 'CM', 5);
insert into player (name, pos, back_num) values ('박민수', 'CM', 28);
insert into player (name, pos, back_num) values ('김치현', 'CM', 36);
insert into player (name, pos, back_num) values ('박형원', 'CM', 66);


insert into game (id, opponent, match_day) values (1, '창평', '2025-01-05');
insert into game (id, opponent, match_day) values (2, '봉알', '2025-01-06');
insert into game (id, opponent, match_day) values (3, '창평', '2025-01-12');
insert into game (id, opponent, match_day) values (4, '봉알', '2025-01-13');
insert into game (id, opponent, match_day) values (5, '창평', '2025-01-19');
insert into game (id, opponent, match_day) values (6, '봉알', '2025-01-20');
--INSERT INTO `player` VALUES
--(1,'신지훈','CM',43);