insert into player (name, pos, back_num) values ('박동렬', 'CM', 8);
insert into player (name, pos, back_num) values ('서호종', 'DF', 20);
insert into player (name, pos, back_num) values ('이창훈', 'CF', 6);
insert into player (name, pos, back_num) values ('송효종', 'CM', 26);
insert into player (name, pos, back_num) values ('이창준', 'CM', 9);
insert into player (name, pos, back_num) values ('국민성', 'CM',14);
insert into player (name, pos, back_num) values ('정형기', 'CM', 40);
insert into player (name, pos, back_num) values ('김용찬', 'CM', 53);
insert into player (name, pos, back_num) values ('안병용', 'CM', 11);
insert into player (name, pos, back_num) values ('조규룡', 'CM', 6);
insert into player (name, pos, back_num) values ('차웅재', 'CM', 99);
insert into player (name, pos, back_num) values ('노형남', 'CM', 3);
insert into player (name, pos, back_num) values ('박정희', 'CM', 52);
insert into player (name, pos, back_num) values ('임성규', 'CM', 72);
insert into player (name, pos, back_num) values ('고준민', 'CM', 32);
insert into player (name, pos, back_num) values ('고대운', 'CM', 16);
insert into player (name, pos, back_num) values ('김현식', 'CM', 46);
insert into player (name, pos, back_num) values ('이우열', 'CM', 27);
insert into player (name, pos, back_num) values ('정한철', 'CM', 2);
insert into player (name, pos, back_num) values ('고영석', 'CM', 18);
insert into player (name, pos, back_num) values ('박주영', 'CM', 24);
insert into player (name, pos, back_num) values ('봉세종', 'CM', 98);
insert into player (name, pos, back_num) values ('박상무', 'CM', 80);
insert into player (name, pos, back_num) values ('김영빈', 'CM', 15);
insert into player (name, pos, back_num) values ('유찬재', 'CM', 45);
insert into player (name, pos, back_num) values ('김영재', 'CM', 38);
insert into player (name, pos, back_num) values ('고재성', 'CM', 17);
insert into player (name, pos, back_num) values ('정태웅', 'CM', 18);
insert into player (name, pos, back_num) values ('김우형', 'CM', 11);
insert into player (name, pos, back_num) values ('신지훈', 'CM', 37);
insert into player (name, pos, back_num) values ('이성완', 'CM', 88);
insert into player (name, pos, back_num) values ('김민석', 'CM', 22);
insert into player (name, pos, back_num) values ('정다운', 'CM', 31);
insert into player (name, pos, back_num) values ('김강민', 'CM', 55);
insert into player (name, pos, back_num) values ('김효준', 'CM', 21);
insert into player (name, pos, back_num) values ('송준민', 'CM', 23);
insert into player (name, pos, back_num) values ('유재호', 'CM', 93);
insert into player (name, pos, back_num) values ('서호연', 'CM', 55);
insert into player (name, pos, back_num) values ('양진서', 'CM', 5);
insert into player (name, pos, back_num) values ('박민수', 'CM', 28);
insert into player (name, pos, back_num) values ('김치현', 'CM', 36);
insert into player (name, pos, back_num) values ('박형원', 'CM', 66);
insert into player (name, pos, back_num) values ('조호현', 'CM', 19);
insert into player (name, pos, back_num) values ('송현민', 'CM', 77);
insert into player (name, pos, back_num) values ('김민재', 'CM', 10);
insert into player (name, pos, back_num) values ('박경호', 'CM', 88);
insert into player (name, pos, back_num) values ('최다일', 'CM', 30);
insert into player (name, pos, back_num) values ('류희창', 'CM', 4);
insert into player (name, pos, back_num) values ('김도영', 'CM', 29);
insert into player (name, pos, back_num) values ('나병근', 'CM', 13);
insert into player (name, pos, back_num) values ('오준엽', 'CM', 7);
insert into player (name, pos, back_num) values ('손주현', 'CM', 39);
insert into player (name, pos, back_num) values ('정주열', 'CM', 47);
insert into player (name, pos, back_num) values ('이승민', 'CM', 35);
insert into player (name, pos, back_num) values ('주태민', 'CM', 41);
insert into player (name, pos, back_num) values ('이정광', 'CM', 1);
insert into player (name, pos, back_num) values ('우수한', 'CM', 43);
insert into player (name, pos, back_num) values ('임영훈', 'GK', 84);
insert into player (name, pos, back_num) values ('임건우', 'CM', 12);
insert into player (name, pos, back_num) values ('전지운', 'CM', 33);
insert into player (name, pos, back_num) values ('고영우', 'CM', 25);
insert into player (name, pos, back_num) values ('김한빈', 'CM', 34);
insert into player (name, pos, back_num) values ('주태민', 'CM', 41);
insert into player (name, pos, back_num) values ('김호영', 'CM', 42);
insert into player (name, pos, back_num) values ('박신일', 'CM', 48);
insert into player (name, pos, back_num) values ('이재원', 'CM', 49);
insert into player (name, pos, back_num) values ('박지훈', 'CM', 50);
insert into player (name, pos, back_num) values ('김종환', 'CM', 71);
insert into player (name, pos, back_num) values ('배신행', 'CM', 94);
insert into player (name, pos, back_num) values ('최유승', 'CM', 81);
insert into player (name, pos, back_num) values ('김승찬', 'CM', 82);
insert into player (name, pos, back_num) values ('김윤태', 'CM', 83);
insert into player (name, pos, back_num) values ('정세용', 'CM', 61);
insert into game (stadium, match_day) values ('창평', '2025-01-05');
insert into game (stadium, match_day) values ('동구다목적', '2025-01-06');
insert into game (stadium, match_day) values ('창평', '2025-01-12');
insert into game (stadium, match_day) values ('동구다목적', '2025-01-13');
insert into game (stadium, match_day) values ('창평', '2025-01-19');
insert into game (stadium, match_day) values ('동구다목적', '2025-01-20');
insert into game (stadium, match_day) values ('동구다목적', '2025-06-10');
insert into game (stadium, match_day) values ('동구다목적', '2025-11-10');
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (1, '도도', 1, 0, 2);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (1, '창평', 2, 2, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (1, '도도', 3, 2, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (1, '창평', 4, 0, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (1, '도도', 5, 3, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (2, '봉알', 1, 1, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (2, '봉알', 2, 2, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (2, '봉알', 3, 4, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (2, '봉알', 4, 3, 4);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '샤크스', 1, 0, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '샤크스', 2, 1, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '창평', 3, 3, 2);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '샤크스', 4, 1, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '창평', 5, 1, 1);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (3, '창평', 6, 5, 0);
insert into quarter (game_id, opponent, quarter_num, point, lose_point) values (8, '창평', 1, 5, 0);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 2, 11);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 2, 50);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 2, 36);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 3, 11);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 3, 46);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 3, 40);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 5, 11);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 5, 50);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 5, 35);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 5, 30);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 5, 30);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 5, 35);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 6, 45);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-06', 6, 27);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 7, 46);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-06', 7, 45);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 8, 15);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 8, 15);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-06', 8, 30);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 8, 15);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-06', 8, 45);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 8, 46);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 9, 30);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 9, 59);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 9, 59);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-06', 9, 27);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 11, 44);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 12, 36);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 12, 2);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-12', 12, 2);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 13, 44);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-05', 13, 67);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 14, 18);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 46);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 46);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 46);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 44);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 40);
insert into point (type, date_info, quarter_id, player_id) values ('ASSIST', '2025-01-12', 15, 40);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 2);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 34);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-12', 15, 34);
insert into point (type, date_info, quarter_id, player_id) values ('GOAL', '2025-01-05', 15, 70);
insert into mom (game_id, player_id) values (1, 11);
insert into mom (game_id, player_id) values (2, 15);
insert into mom (game_id, player_id) values (2, 19);
insert into mom (game_id, player_id) values (3, 44);
insert into mom (game_id, player_id) values (3, 58);
insert into attend (game_id, player_id) values (1, 30);
insert into attend (game_id, player_id) values (1, 66);
insert into attend (game_id, player_id) values (1, 36);
insert into attend (game_id, player_id) values (1, 48);
insert into attend (game_id, player_id) values (1, 53);

